### ISSUE TITLE
Help?

### ISSUE THREAD

**Issue by d34d10cc** [goonstation/ProcessScheduler#4]
Just gonna copy my issue from para:
Not really an issue, but when I try to open my testing server, it loads, and after ~10 seconds, I get an error and the server closes:
PRECISE_TIMER_AVAILABLE is defined in btime.dm, but calling the btime library failed: Unable to load library btime.dll
This is a fatal error. The world will now shut down.
ERROR: Hook '/hook/startup/proc/checkbtime' failed or runtimed.
The btime.dll file is in the same directory as my .dmb file.

**Comment by volundr-** [comment]
Sometimes you have to put btime.dll in the same place as DreamDaemon.exe.

**Comment by d34d10cc** [comment]
Ah, I'll try and report back.

**Comment by d34d10cc** [comment]
Nope.

**Comment by volundr-** [comment]
Ok, did you check the windows event viewer? It may need a runtime that you dont have installed.

**Comment by d34d10cc** [comment]
Nothing there.

**Comment by volundr-** [comment]
Try putting it in system32

**Comment by d34d10cc** [comment]
Still nope.

**Comment by volundr-** [comment]
I dunno man... hit me up again next week.

**Comment by d34d10cc** [comment]
Alright, I'll try to tinker myself a lil bit

**Comment by CrAzYPiLoT-SS13** [comment]
Bumpity

**Comment by d34d10cc** [comment]
Magically resolved itself after the newest byond update
