### ISSUE TITLE
scheck too aggressive?

### ISSUE THREAD

**Issue by Fox-McCloud** [goonstation/ProcessScheduler#5]
One thing I've noticed, when profiling the scheduler is abnormally high differences between processScheduler/process()'s CPU time and it's real time (this is also the case for individual subprocesses, of course, as well)---the only reason that this would happen is because of `scheck` under individual processes (have proved this out too). 

The odd thing is, `scheck` seems to like to defer---a LOT, even when it's not necessary to do so; even at a steady state where nothing major is happening on the server and it's just at background levels, `scheck` will defer quite a bit despite the CPU not hitting anywhere close to 100 on the actual machine (by internal or BYOND measurement).

I realize that btime.dll was created to more accurate measurement of the current tick duration, but is it possible it's a bit too aggressive and is causing `scheck` to defer, even when it's not needed?

This would seem a bit problematic considering that deferring when there's no reason to will just end up wasting CPU and end up increasing the load on the next tick when there's no explicit reason to.

Also, is the btime.dll source available anywhere, @volundr- ?

**Comment by j-mie** [comment]
@Fox-McCloud btime source is here: https://github.com/goonstation/ProcessScheduler/blob/master/btime/btime.cpp

**Comment by volundr-** [comment]
@Fox-McCloud - btime was created to fix that exact problem. In-game time sources are not accurate enough to provide really accurate process deferment. On some systems, it's too aggressive, on others, not enough. 

There's instructions for compiling btime in the btime directory.

**Comment by Fox-McCloud** [comment]
@volundr- 

We do use btime; you helped us get it up and running; our server will literally not launch if we don't have btime---what I'm saying is, even under practically no load with only a single player, `scheck` is causing a lot of deferring despite the CPU (by internal and external measurements) not being anywhere close to overloaded or the tick being anywhere close to being driven into overtime.

@JamieH 

Thanks!
